### ISSUE TITLE
Generates duplicate methods

### ISSUE THREAD

**Issue by Pikachews** [HamedFathi/MockableStaticGenerator#2]
I'm trying to use this on an external static class (`System.IO.Compression.ZipFile`), but the result appears to generate duplicate methods many times.

![image](https://user-images.githubusercontent.com/5668416/190927086-89fa66e3-bc84-4b4c-8675-b2a2ebbe4bcb.png)

Possibly due to being a partial class? Not sure.

**Comment by HamedFathi** [comment]
Thanks for the issue, I hope the new version work for you.

![Screenshot_2](https://user-images.githubusercontent.com/8418700/191329159-38815fe0-fcb8-4237-b5ae-9b647bbdb03d.png)
